### ISSUE TITLE
ServiceNow Import fail issue "Repository authentication failed, check credentials. Make sure the user has both read and write access"

### ISSUE THREAD

**Issue by canderson123** [byukich/x_snc_aws_sns#3]
https://github.com/byukich/x_snc_aws_sns/issues/1 

I am referencing an issue reported in April. I am in the Quebec release (also tried Rome) on a personal instance and have looked at this at least 3 hours today. I am unable to upload using my forked instance using Personal Access Token on Git side and Basic Authentication on ServiceNow side using the token as my password. The .git file I am attempting to import which is giving me the same authentication failed issue is:

https://github.com/ServiceNow/devtraining-needit-quebec

any ideas? seems ServiceNow is not commenting on this issue and if they are, they are using the same solution as reported in previous ticket that does not work. might have to try yet ANOTHER release but so far I am 0-2

**Comment by canderson123** [comment]
I discovered the problem was with the keychain for PAT on my MAC. I moved things over to my Dell and it worked fine. closing ticket

**Comment by thisnameissoclever** [comment]
I recently wrote a 'ServiceNow Pro Tips' article on this, which teaches you:



1. How to change which GitHub / repository your ServiceNow application in Studio

2. How to update your GitHub repo credentials in ServiceNow

3. How to generate ECDSA SSH keys and link your ServiceNow application with GitHub using SSH (including the new GitHub rule against using insecure RSA keys) - since GitHub no longer supports basic auth or RSA SSH keys

4. How to generate/link your SSH API key-pair with GitHub and ServiceNow, using your public/private keys



You can see the full article with detailed step-by-step instructions, [here:](https://snprotips.com/blog/2022/3/4/how-to-change-servicenow-applications-repositoryurl%20)

https://snprotips.com/blog/2022/3/4/how-to-change-servicenow-applications-repositoryurl
